name: DevAthlon
version: 1.0
authors: [qlow, LabyStudio]
main: net.laby.devathlon.DevAthlon
description: Do fights with your ship(s) and get better ships!

commands:
  game:
    description: Game-setup command
    usage: /<command>
  shipmatic:
    description: create schematics
    usage: /<command> save <name>